# Generated by Django 3.1 on 2020-08-12 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0007_remove_client_ebooks'),
        ('productos', '0005_auto_20200812_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.client')),
            ],
        ),
    ]
