# Generated by Django 3.1 on 2020-08-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pay',
            field=models.BooleanField(default=False),
        ),
    ]
