# Generated by Django 3.1 on 2020-08-08 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_auto_20200808_1939'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='adm',
        ),
    ]
