# Generated by Django 3.1 on 2020-08-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20200812_0715'),
        ('cuentas', '0005_auto_20200812_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ebooks',
            field=models.ManyToManyField(blank=True, to='productos.Producto'),
        ),
    ]
