# Generated by Django 3.1 on 2020-08-12 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0006_client_ebooks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='ebooks',
        ),
    ]
